### PR TITLE
Add expiry date to cookie store

### PR DESCRIPTION
**Pull request by clodeindustrie**
Just letting you have a look first and then I'll post a PR for the original Repo.
https://trello.com/c/9X0nZ8MX/373-move-vignette-variant-tracking-to-its-own-cookie

### CODE REVIEW

**Comment by michaelbaudino** [comment]
Code looks good @clodeindustrie (it even follows original codestyle :+1: ). Did you test it in a real browser ?

**Comment by clodeindustrie** [comment]
Yup, tested on `Frontend`, the trick here is that `cookies` on Rails can take a `:value` key and an expiry date in a hash but will return only the `:value` value when retrieving it.
```ruby
cookies[:v] = { value: "toto", expires: Date.now }
put cookies[:v] # "toto"
```

**Comment by novikserg** [comment]
Are we planning to PR that to original Vignette repo?

**Comment by clodeindustrie** [comment]
yes we are @novikserg

**Comment by novikserg** [comment]
looks good

**Comment by novikserg** [comment]
@clodeindustrie to boost it up you can fork that to your Github profile and PR from yours rather Kyero

**Pull request merged**
